changed text top.ejs detailes to details
shotYazaki/test-app pull request #11
Opened 2020-12-04 07:36 UTC by shotYazaki

2020-12-04 09:34 UTC, yosiyuki requested changes

2020-12-04 09:34 UTC, yosiyuki commented on views/top.ejs
@shotYazaki ↑ ここのなにもない行を消してください

2020-12-04 09:36 UTC, yosiyuki commented
https://github.com/shotYazaki/test-app/issues/10

2020-12-06 02:19 UTC, shotYazaki commented
一応何もない行を消しました

2020-12-24 06:25 UTC, merged